environment                         = "dev"
project                             = "AlpineBot"
owner                               = "Fred"
department                          = "IT Department"
location                            = "SwitzerlandNorth"