#### Variables values ####
az_backend_rg_name = "dev-bkd-alpinebot"
az_backend_sa_name = "devbkdalpinebotsa"
az_backend_container_name = "dev-bkd-alpinebot-co"
az_rg_name = "dev-alpinebot"
az_kv_name = "dev-alpinebot-kv"
az_openai_key_name = "dev-alpinebot-openai-key"
terraform_key = "dev-terraform-state"
apbotinsights_name = "dev-apbotinsights"
wap_sp_name = "dev-alpinebot-sp"
wap_website_name = "dev-alpinebot-as"
alpinebotaiact = "dev-alpinebot-act"
alpinebotaidepl = "dev-alpinebot-dpl"